package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Ejercicio generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "ejercicio")
@XmlType(propOrder = {"nombre"})
public class Ejercicio implements java.io.Serializable {

    @XmlAttribute
    private Integer id;
    @XmlElement
    private String nombre;
    @Transient
    private LinkBean link;

    public Ejercicio() {
    }

    public Ejercicio(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public LinkBean getLink() {
        this.link = new LinkBean("self", "http://localhost:8080/Proyecto/webservice/ejercicios/" + this.getId() + "/tablas");
        return link;
    }

    public void setLink(LinkBean link) {
        this.link = link;
    }

}
