package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Ejercicio generated by hbm2java
 */
@XmlRootElement
@XmlType(propOrder = {"id", "nombre"})
public class Ejercicio implements java.io.Serializable {

    private Integer id;
    private String nombre;

    public Ejercicio() {
    }

    public Ejercicio(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

//    @XmlElement
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @XmlElement
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
