package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Lineasejercicio generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "lineasejercicio")
@XmlType(propOrder = {"tabla","dia", "ejercicio", "orden", "series", "repeticiones", "peso", "link"})
public class Lineasejercicio implements java.io.Serializable {

    @XmlAttribute
    private int id;
    @XmlElement
    private Integer tabla;
    @XmlElement
    private String dia;
    @XmlElement
    private int orden;
    @XmlElement
    private Integer series;
    @XmlElement
    private Integer repeticiones;
    @XmlElement
    private Integer peso;
    @XmlElement
    private Ejercicio ejercicio;
    @Transient
    private LinkBean link;


    public Lineasejercicio() {
    }

    public Lineasejercicio(int id, String dia, int orden, Integer series, Integer repeticiones, Integer peso, Ejercicio ejercicio, Integer tabla) {
        this.id = id;
        this.dia = dia;
        this.orden = orden;
        this.series = series;
        this.repeticiones = repeticiones;
        this.peso = peso;
        this.ejercicio = ejercicio;
        this.tabla = tabla;
    }

    public Lineasejercicio(int id, Integer tabla, String dia, int orden, Integer series, Integer repeticiones, Integer peso, Ejercicio ejercicio, LinkBean link) {
        this.id = id;
        this.tabla = tabla;
        this.dia = dia;
        this.orden = orden;
        this.series = series;
        this.repeticiones = repeticiones;
        this.peso = peso;
        this.ejercicio = ejercicio;
        this.link = link;
    }
    
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDia() {
        return dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    public int getOrden() {
        return orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public Integer getSeries() {
        return series;
    }

    public void setSeries(Integer series) {
        this.series = series;
    }

    public Integer getRepeticiones() {
        return repeticiones;
    }

    public void setRepeticiones(Integer repeticiones) {
        this.repeticiones = repeticiones;
    }

    public Integer getPeso() {
        return peso;
    }

    public void setPeso(Integer peso) {
        this.peso = peso;
    }

    public Ejercicio getEjercicio() {
        return ejercicio;
    }

    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }

    public Integer getTabla() {
        return tabla;
    }

    public void setTabla(Integer tabla) {
        this.tabla = tabla;
    }

    @XmlElement
    public LinkBean getLink() {
        this.link = new LinkBean("self", "http://localhost:8080/Proyecto/webservice/tablas/" + this.getTabla());
        return link;
    }

    public void setLink(LinkBean link) {
        this.link = link;
    }
}
