package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Lineasejercicio generated by hbm2java
 */
@XmlRootElement
@XmlType(propOrder = {"id", "tabla", "dia", "orden", "series", "repeticiones", "peso", "ejercicio"})
public class Lineasejercicio implements java.io.Serializable {

    private int id;
    private int tabla;
    private String dia;
    private int orden;
    private Integer series;
    private Integer repeticiones;
    private Integer peso;
    private Ejercicio ejercicio;

    public Lineasejercicio() {
    }

    public Lineasejercicio(int id, int tabla, String dia, int orden, Integer series, Integer repeticiones, Integer peso, Ejercicio ejercicio) {
        this.id = id;
        this.tabla = tabla;
        this.dia = dia;
        this.orden = orden;
        this.series = series;
        this.repeticiones = repeticiones;
        this.peso = peso;
        this.ejercicio = ejercicio;
    }

    @XmlElement
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @XmlElement
    public int getTabla() {
        return this.tabla;
    }

    public void setTabla(int tabla) {
        this.tabla = tabla;
    }

    @XmlElement
    public String getDia() {
        return this.dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    @XmlElement
    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    @XmlElement
    public Integer getSeries() {
        return this.series;
    }

    public void setSeries(Integer series) {
        this.series = series;
    }

    @XmlElement
    public Integer getRepeticiones() {
        return this.repeticiones;
    }

    public void setRepeticiones(Integer repeticiones) {
        this.repeticiones = repeticiones;
    }

    @XmlElement
    public Integer getPeso() {
        return this.peso;
    }

    public void setPeso(Integer peso) {
        this.peso = peso;
    }

    @XmlElement
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }

    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }

}
