package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

/**
 * Lineasejercicios generated by hbm2java
 */
public class Lineasejercicio implements java.io.Serializable {

    private int id;
    private int ejercicio;
    private int tabla;
    private String dia;
    private int orden;
    private Integer series;
    private Integer repeticiones;
    private Integer peso;
    private Ejercicio ejercicios;

    public Lineasejercicio() {
    }

    public Lineasejercicio(int id, int ejercicio, int tabla, int orden) {
        this.id = id;
        this.ejercicio = ejercicio;
        this.tabla = tabla;
        this.orden = orden;
    }

    public Lineasejercicio(int id, int ejercicio, int tabla, String dia, int orden, Integer series, Integer repeticiones, Integer peso, Ejercicio ejercicios) {
        this.id = id;
        this.ejercicio = ejercicio;
        this.tabla = tabla;
        this.dia = dia;
        this.orden = orden;
        this.series = series;
        this.repeticiones = repeticiones;
        this.peso = peso;
        this.ejercicios = ejercicios;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getEjercicio() {
        return this.ejercicio;
    }

    public void setEjercicio(int ejercicio) {
        this.ejercicio = ejercicio;
    }

    public int getTabla() {
        return this.tabla;
    }

    public void setTabla(int tabla) {
        this.tabla = tabla;
    }

    public String getDia() {
        return this.dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    public int getOrden() {
        return this.orden;
    }

    public void setOrden(int orden) {
        this.orden = orden;
    }

    public Integer getSeries() {
        return this.series;
    }

    public void setSeries(Integer series) {
        this.series = series;
    }

    public Integer getRepeticiones() {
        return this.repeticiones;
    }

    public void setRepeticiones(Integer repeticiones) {
        this.repeticiones = repeticiones;
    }

    public Integer getPeso() {
        return this.peso;
    }

    public void setPeso(Integer peso) {
        this.peso = peso;
    }

    public Ejercicio getEjercicios() {
        return this.ejercicios;
    }

    public void setEjercicios(Ejercicio ejercicios) {
        this.ejercicios = ejercicios;
    }

}
