package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Monitor generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "monitor")
@XmlType(propOrder = {"nombre", "apellidos", "administrador", "link"})
public class Monitor implements java.io.Serializable {

    @XmlAttribute
    private Integer id;
    @XmlElement
    private String nombre;
    @XmlElement
    private String apellidos;
    @XmlElement
    private Integer administrador;
    @Transient
    private LinkBean link;

    public Monitor() {
    }

    public Monitor(Integer id) {
        this.id = id;
    }

    public Monitor(String nombre) {
        this.nombre = nombre;
    }

    public Monitor(String nombre, String apellidos) {
        this.nombre = nombre;
        this.apellidos = apellidos;
    }

    public Monitor(String nombre, String apellidos, Integer administrador) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.administrador = administrador;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Integer isAdministrador() {
        return this.administrador;
    }

    public void setAdministrador(Integer administrador) {
        this.administrador = administrador;
    }

    @XmlElement
    public LinkBean getLink() {
        this.link = new LinkBean("self", "http://localhost:8080/Proyecto/webservice/monitores/" + this.getId() + "/alumnos");
        return link;
    }

    public void setLink(LinkBean link) {
        this.link = link;
    }
}
