package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

/**
 * Monitor generated by hbm2java
 */
public class Monitor implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String apellidos;
    private Tabla tablas;

    public Monitor() {
    }

    public Monitor(String nombre) {
        this.nombre = nombre;
    }

    public Monitor(String nombre, String apellidos, Tabla tablas) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.tablas = tablas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Tabla getTablas() {
        return this.tablas;
    }

    public void setTablas(Tabla tablas) {
        this.tablas = tablas;
    }

}
