package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Monitor generated by hbm2java
 */
@XmlRootElement
@XmlType(propOrder = {"id", "nombre", "apellidos"})
public class Monitor implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String apellidos;

    public Monitor() {
    }

    public Monitor(String nombre) {
        this.nombre = nombre;
    }

    public Monitor(String nombre, String apellidos) {
        this.nombre = nombre;
        this.apellidos = apellidos;
    }

    @XmlElement
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @XmlElement
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @XmlElement
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

}
