package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tabla generated by hbm2java
 */
public class Tabla implements java.io.Serializable {

    private Integer id;
    private Monitor alumno;
    private Date fechaCreacion;
    private Date fechainicio;
    private Date fechaCambio;
    private BigDecimal peso;
    private Integer estatura;
    private String objetivos;

    public Tabla() {
    }

    public Tabla(Integer id, Monitor alumno, Date fechaCreacion, Date fechainicio, Date fechaCambio, BigDecimal peso, Integer estatura, String objetivos) {
        this.id = id;
        this.alumno = alumno;
        this.fechaCreacion = fechaCreacion;
        this.fechainicio = fechainicio;
        this.fechaCambio = fechaCambio;
        this.peso = peso;
        this.estatura = estatura;
        this.objetivos = objetivos;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Monitor getAlumno() {
        return alumno;
    }

    public void setAlumno(Monitor alumno) {
        this.alumno = alumno;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechainicio() {
        return fechainicio;
    }

    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    public Date getFechaCambio() {
        return fechaCambio;
    }

    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }

    public BigDecimal getPeso() {
        return peso;
    }

    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }

    public Integer getEstatura() {
        return estatura;
    }

    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }

    public String getObjetivos() {
        return objetivos;
    }

    public void setObjetivos(String objetivos) {
        this.objetivos = objetivos;
    }

}
