package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tabla generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlRootElement(name = "tabla")
@XmlType(propOrder = {"alumno", "monitor", "fechaCreacion", "fechaInicio", "fechaCambio", "peso", "estatura", "objetivos", "link"})
public class Tabla implements java.io.Serializable {

    @XmlAttribute
    private Integer id;
    @XmlElement
    private Alumno alumno;
    @XmlElement
    private Monitor monitor;
    @XmlElement
    private Date fechaCreacion;
    @XmlElement
    private Date fechaInicio;
    @XmlElement
    private Date fechaCambio;
    @XmlElement
    private BigDecimal peso;
    @XmlElement
    private Integer estatura;
    @XmlElement
    private String objetivos;
    @Transient
    private LinkBean link;

    public Tabla() {
    }

    public Tabla(Integer id, Date fechaCreacion, Date fechainicio, Date fechaCambio, BigDecimal peso, Integer estatura, String objetivos) {
        this.id = id;
        this.fechaCreacion = fechaCreacion;
        this.fechaInicio = fechainicio;
        this.fechaCambio = fechaCambio;
        this.peso = peso;
        this.estatura = estatura;
        this.objetivos = objetivos;
    }

    public Tabla(Integer id, Alumno alumno, Monitor monitor, Date fechaCreacion, Date fechaInicio, Date fechaCambio, BigDecimal peso, Integer estatura, String objetivos) {
        super();
        this.id = id;
        this.alumno = alumno;
        this.monitor = monitor;
        this.fechaCreacion = fechaCreacion;
        this.fechaInicio = fechaInicio;
        this.fechaCambio = fechaCambio;
        this.peso = peso;
        this.estatura = estatura;
        this.objetivos = objetivos;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Alumno getAlumno() {
        return alumno;
    }

    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    public Monitor getMonitor() {
        return monitor;
    }

    public void setMonitor(Monitor monitor) {
        this.monitor = monitor;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechainicio() {
        return fechaInicio;
    }

    public void setFechainicio(Date fechainicio) {
        this.fechaInicio = fechainicio;
    }

    public Date getFechaCambio() {
        return fechaCambio;
    }

    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }

    public BigDecimal getPeso() {
        return peso;
    }

    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }

    public Integer getEstatura() {
        return estatura;
    }

    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }

    public String getObjetivos() {
        return objetivos;
    }

    public void setObjetivos(String objetivos) {
        this.objetivos = objetivos;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @XmlElement
    public LinkBean getLink() {
        this.link = new LinkBean("self", "http://localhost:8080/Proyecto/webservice/tablas/" + this.getId() + "/lineas");
        return link;
    }

    public void setLink(LinkBean link) {
        this.link = link;
    } 
}
