package pojos;
// Generated 27-feb-2015 11:03:57 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tabla generated by hbm2java
 */
@XmlRootElement
@XmlType(propOrder = {"id", "alum", "apellidos", "fechaAlta", "fechaNacimiento", "cuadroClinico"})
public class Tabla implements java.io.Serializable {

    private Integer id;
    private Alumno alumno;
    private Monitor monitor;
    private Date fechaCreacion;
    private Date fechainicio;
    private Date fechaCambio;
    private BigDecimal peso;
    private Integer estatura;
    private String objetivos;

    public Tabla() {
    }

    public Tabla(Integer id, Alumno alumno, Monitor monitor, Date fechaCreacion, Date fechainicio, Date fechaCambio, BigDecimal peso, Integer estatura, String objetivos) {
        this.id = id;
        this.alumno = alumno;
        this.monitor = monitor;
        this.fechaCreacion = fechaCreacion;
        this.fechainicio = fechainicio;
        this.fechaCambio = fechaCambio;
        this.peso = peso;
        this.estatura = estatura;
        this.objetivos = objetivos;
    }

    @XmlElement
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @XmlElement
    public Alumno getAlumno() {
        return alumno;
    }

    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    @XmlElement
    public Monitor getMonitor() {
        return monitor;
    }

    public void setMonitor(Monitor monitor) {
        this.monitor = monitor;
    }

    @XmlElement
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @XmlElement
    public Date getFechainicio() {
        return fechainicio;
    }

    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @XmlElement
    public Date getFechaCambio() {
        return fechaCambio;
    }

    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }

    @XmlElement
    public BigDecimal getPeso() {
        return peso;
    }

    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }

    @XmlElement
    public Integer getEstatura() {
        return estatura;
    }

    public void setEstatura(Integer estatura) {
        this.estatura = estatura;
    }

    @XmlElement
    public String getObjetivos() {
        return objetivos;
    }

    public void setObjetivos(String objetivos) {
        this.objetivos = objetivos;
    }

}
